spring:
  profiles:
    include: oauth, apiKey
    group:
      local: local
      prod : prod
      dev : dev
  jpa:
    database: mysql
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate