application:
  title: 새식일기
  version: 1.0v

spring:
  profiles:
    include: oauth, apiKey
    group:
      local: local
      prod : prod
      dev : dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

logging:
  level:
#    root: debug
#    org:
#      hibernate: debug
    sql: debug

