# local
spring:
  config:
    activate:
      on-profile: local

  datasource:
    jdbc-url: ENC(XDuOfsJUWRovzOS5LjfBEcxhXWnLABmB/7eIYP0uBVQSo8f8Jbi6Pg==)
    driver-class-name: org.h2.Driver
    username: ENC(Cobw7rxXgtpI+8MddkLPdA==)
    password: ENC(gjCAJH5mJZ2sDNyZ5rvR9Q==)

  h2:
    console: true

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MariaDBDialect

  database:
#    platform: mariadb

mybatis:
  configuration:
    map-underscore-to-camel-case: true

    data:
      mongodb:
        host: localhost
        port: 27017
        authentication-database: admin
        database: sample

file.dir: C:/saesigDiary/file/
