# local
spring:
  config:
    activate:
      on-profile: local

  datasource:
    jdbc-url: ENC(0SIVOUq3nPqZpySfAmPv5HiCJq/cA4X+cThawAS48Fdi4HxmSaPCDg==)
    driver-class-name: org.h2.Driver
    username: ENC(pOYIaEb0HWP+CrJw6QOOLA==)
    password: ENC(zu7yt2tvASOJs0QweZw/rA==)

  h2:
    console: true

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MariaDBDialect

  database:
#    platform: mariadb

mybatis:
  configuration:
    map-underscore-to-camel-case: true

    data:
      mongodb:
        host: localhost
        port: 27017
        authentication-database: admin
        database: sample

file.dir: C:/saesigDiary/file/
