#default
application:
  title: 새식일기
  version: 1.0v

spring:
  profiles:
    include: oauth, apiKey, s3
    group:
      local: local
      prod : prod
      dev : dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  session:
    store-type: jdbc

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(Tq1mWDEq6K5WoBhsTofIJv8V0GE8ARF7q2jOvDFkG6AylXeuVRwWGg==)
    password: ENC(+dV0xeVvNJDt6FXGe+CSK44tFILZusEDLhnusUQ1kBY=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
          transport: smtp

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MariaDBDialect



mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #    mapper-locations: classpath:mybatis/mappers/**/*.xml

    data:
      mongodb:
        host: ENC(2J77q2vvF7KPM0R2h6gRrJUSVKfdmuh2)
        port: 27017
        authentication-database: admin
        database: sample



decorator:
  datasource:
    p6spy:
      enable-logging: true




management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
#      show-details: always
      show-components: always
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true


info:
  app:
    name: hello-actuator
    company: mekc-saesig

server:
  tomcat:
    mbeanregistry:
      enabled: true

file.dir: C:/saesigDiary/file/

springdoc:
  packages-to-scan: com.saesig.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
      operationsSorter: alpha
      displayRequestDuration: true

--- #local
spring:
  config:
    activate:
      on-profile: local

  datasource:
    jdbc-url: jdbc:mariadb://localhost:3306/saesig?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  sql:
    init:
      mode: always
      data-locations: classpath*:/data-mysql.sql
      schema-locations: classpath*:/schema-mysql.sql

file.dir: C:/saesigDiary/file/

favicon:
  file-dir: C:/saesigDiary/file/favicon/   
kakao-thumbnail:
  file-dir: C:/saesigDiary/file/kakaoThumbnail/

logging:
  level:  # 각 package 별로 로깅 레벨을 지정할 수 있다.
    root : INFO
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: INFO              # TRACE org.hibernate.type.descriptor.sql.BasicBinder.bind 로그를 지웁니다.
        SQL: INFO

--- #dev
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    jdbc-url: ENC(9UYIlV52PeveFLJ2yIXgEI7JMqjFgcQGerCrApXG5Ry4gzvJOR5h/jT/oKy3DVBSWWQIIA3QYbAgJyWtwU5jP5WotTshWxaAnZ2NxlqLaQPi7xXR24Hr2tvM/dN+yYR7)
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(95ePKgRxP7hUPJNo9E65UQ==)
    password: ENC(NYMTRtIaUjs1AmlSar9tmZUsPqDShDg5)

file.dir: /saesig/dev/file/

favicon:
  file-dir: /saesig/dev/file/favicon/
kakao-thumbnail:
  file-dir: /saesig/dev/file/kakaoThumbnail/


--- #prod
spring:
  config:
    activate:
      on-profile: prod

decorator:
  datasource:
    p6spy:
      enable-logging: false

--- #defaults